services:
  web:
    container_name: web_server
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080 
    depends_on:
      - mysqldb
    volumes:
      - ./app/target:/app
    networks:
     - app-network

  
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: sad_db
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    networks:
      app-network:
        aliases:
          - dbAddress
      
networks:
  app-network:

