# Specifica l'immagine di base che include Maven
FROM openjdk:latest

# Imposta la directory di lavoro
WORKDIR /app

# Esponi la porta dell'applicazione
EXPOSE 8080

# Comando per avviare l'applicazione Spring Boot
CMD ["java", "-jar", "project-0.0.1-SNAPSHOT.jar"] 